export const stringsAutenticacao = {
  tituloLogin: "Entrar",
  tituloCadastro: "Cadastrar",
  tituloLogout: "Sair do Sistema",
  descricaoLogin: "Entre na sua conta do sistema financeiro",
  descricaoCadastro: "Crie sua conta para começar",
  botaoLogin: "Entrar",
  botaoCadastro: "Cadastrar",
  botaoLogout: "Sair",
  botaoCancelar: "Cancelar",
  botaoConfirmar: "Confirmar",
  linkParaCadastro: "Cadastre-se",
  linkParaLogin: "Faça login",
  textoSemConta: "Não tem uma conta? ",
  textoComConta: "Já tem uma conta? ",
  carregandoLogin: "Entrando...",
  carregandoCadastro: "Cadastrando...",
  carregandoLogout: "Saindo...",
  sucessoLogin: "Login realizado com sucesso!",
  sucessoCadastro: "Cadastro realizado com sucesso!",
  sucessoCadastroDescricao:
    "Sua conta foi criada! Agora você pode fazer login com suas credenciais.",
  sucessoLogout: "Logout realizado com sucesso!",
  tituloConfirmacaoLogout: "Confirmar Logout",
  mensagemConfirmacaoLogout: "Você tem certeza que deseja sair do sistema?",
  credenciaisInvalidas: "Email ou senha incorretos",
  emailJaExiste: "Este email já está em uso",
  senhaFraca: "Senha muito fraca",
  erroConexao: "Erro de conexão. Verifique sua internet.",
  sessaoExpirada: "Sessão expirada. Faça login novamente.",
  tituloErroCredenciais: "Erro nas Credenciais",
  mensagemErroCredenciais:
    "Você errou suas credenciais ou não possui conta, deseja cadastrar?",
  botaoCadastrarAgora: "Cadastrar Agora",
  botaoTentarNovamente: "Tentar Novamente",
  labelEmail: "Email",
  labelSenha: "Senha",
  labelNomeCompleto: "Nome Completo",
  labelNovaSenha: "Nova Senha",
  labelConfirmarSenha: "Confirmar Senha",
  placeholderEmail: "Digite seu email",
  placeholderSenha: "Digite sua senha",
  placeholderNomeCompleto: "Digite seu nome completo",
  placeholderNovaSenha: "Digite a nova senha",
  placeholderConfirmarSenha: "Confirme a nova senha",
  emailObrigatorio: "Email é obrigatório",
  emailInvalido: "Email inválido",
  senhaObrigatoria: "Senha é obrigatória",
  senhaMinima: "Senha deve ter pelo menos 6 caracteres",
  nomeObrigatorio: "Nome completo é obrigatório",
  nomeMinimo: "Nome deve ter pelo menos 2 caracteres",
  novaSenhaObrigatoria: "Nova senha é obrigatória",
  confirmarSenhaObrigatoria: "Confirmação de senha é obrigatória",
};
