export const stringsCategorias = {
  categoria: "Categoria",
  categorias: "Categorias",
  titulo: "Gerenciar Categorias",
  novaCategoria: "Nova Categoria",
  editarCategoria: "Editar Categoria",
  listagemTitulo: "Suas Categorias",
  descricaoSecao: "Organize suas transações criando categorias personalizadas",
  nome: "Nome da Categoria",
  nomeCampo: "Nome",
  cor: "Cor",
  descricao: "Descrição",
  descricaoCampo: "Descrição (opcional)",
  placeholderNome: "Digite o nome da categoria",
  placeholderDescricao: "Descrição da categoria (opcional)",
  descricaoPlaceholder: "Ex: Gastos com alimentação e restaurantes",
  nenhumaCategoria: "Nenhuma categoria encontrada",
  crieAPriveira: "Crie sua primeira categoria para organizar suas transações",
  nomeObrigatorio: "Nome da categoria é obrigatório",
  nomeMinimo: "Nome deve ter pelo menos 2 caracteres",
  corObrigatoria: "Cor é obrigatória",
  categoriaSalva: "Categoria salva com sucesso!",
  categoriaRemovida: "Categoria removida com sucesso!",
  erroSalvar: "Erro ao salvar categoria",
  erroRemover: "Erro ao remover categoria",
  erroCarregar: "Erro ao carregar categorias",
  confirmarRemocao: "Confirmar Remoção",
  confirmarRemocaoTexto: "Tem certeza que deseja remover a categoria",
  remover: "Remover",
  categoriaEmUso:
    "Esta categoria está sendo usada em transações e não pode ser removida",
};
