export const stringsGerais = {
  nomeAplicacao: "Sistema Financeiro",
  dashboard: "Dashboard",
  bemVindo: "Bem-vindo",
  bemVindoCompleto: "Bem-vindo",
  transacoes: "Transações",
  categorias: "Categorias",
  resumoMensal: "Resumo Mensal",
  gerencieTransacoesTexto: "Gerencie suas receitas e despesas financeiras",
  organizeCategorias: "Organize suas transações em categorias personalizadas",
  acompanheResumo: "Acompanhe seus resultados mensais e anuais",
  statusSistema: " Status do Sistema",
  sistemaSignals: "Sistema de estado com Signals",
  acessar: "Acessar",
  verificarSaude: "Verificar Saúde",
  saudeAPI: "Saúde da API",
  saudeSistema: "Sistema funcionando normalmente",
  verificandoSaude: "Verificando saúde do sistema...",
  saudeOK: " Sistema saudável",
  saudeErro: "Problema no sistema",
  desenvolvedor: "Desenvolvido por Matheus Faustino",
  saudacaoUsuario: "Olá, {nome}!",
  ok: "OK",
  cancelar: "Cancelar",
  salvar: "Salvar",
  atualizar: "Atualizar",
  editar: "Editar",
  excluir: "Excluir",
  adicionar: "Adicionar",
  buscar: "Buscar",
  filtrar: "Filtrar",
  limpar: "Limpar",
  atualizar: "Atualizar",
  voltar: "Voltar",
  proximo: "Próximo",
  anterior: "Anterior",
  carregando: "Carregando...",
  salvando: "Salvando...",
  excluindo: "Excluindo...",
  buscando: "Buscando...",
  erro: "Erro",
  sucesso: "Sucesso",
  atencao: "Atenção",
  informacao: "Informação",
  erroGeral: "Ocorreu um erro inesperado. Tente novamente.",
  erroConexao: "Erro de conexão. Verifique sua internet.",
  erroServidor: "Erro no servidor. Tente novamente mais tarde.",
  naoEncontrado: "Recurso não encontrado.",
  naoAutorizado: "Acesso não autorizado.",
  acessoNegado: "Acesso negado.",
  confirmarExclusao: "Tem certeza que deseja excluir?",
  confirmarAcao: "Confirmar ação",
  alteracoesNaoSalvas: "Existem alterações não salvas. Deseja continuar?",
  inicio: "Início",
  perfil: "Perfil",
  settings: "Configurações",
  help: "Ajuda",
  about: "Sobre",
  required: "Campo obrigatório",
  invalid: "Valor inválido",
  tooShort: "Muito curto",
  tooLong: "Muito longo",
  page: "Página",
  of: "de",
  itemsPerPage: "Itens por página",
  noResults: "Nenhum resultado encontrado",
  today: "Hoje",
  yesterday: "Ontem",
  thisWeek: "Esta semana",
  thisMonth: "Este mês",
  thisYear: "Este ano",
};
