export const stringsResumo = {
  resumoMensal: "Resumo Mensal",
  periodo: "Período",
  resumoDe: "Resumo de",
  mes: "Mês",
  ano: "Ano",
  meses: {
    janeiro: "Janeiro",
    fevereiro: "Fevereiro",
    marco: "Março",
    abril: "Abril",
    maio: "Maio",
    junho: "Junho",
    julho: "Julho",
    agosto: "Agosto",
    setembro: "Setembro",
    outubro: "Outubro",
    novembro: "Novembro",
    dezembro: "Dezembro",
  },
  arrayMeses: [
    "Janeiro",
    "Fevereiro",
    "Março",
    "Abril",
    "Maio",
    "Junho",
    "Julho",
    "Agosto",
    "Setembro",
    "Outubro",
    "Novembro",
    "Dezembro",
  ],
  atualizar: "Atualizar",
  carregando: "Carregando",
  carregandoResumo: "Carregando resumo",
  receitas: "Receitas",
  despesas: "Despesas",
  saldoPositivo: "Saldo Positivo",
  saldoNegativo: "Saldo Negativo",
  saldoNeutro: "Saldo Neutro",
  estatisticasPeriodo: "Estatísticas do Período",
  totalTransacoes: "Total de Transações",
  receitasPorCategoria: "Receitas por Categoria",
  despesasPorCategoria: "Despesas por Categoria",
  principaisTransacoes: "Principais Transações",
  nenhumDadoEncontrado: "Nenhum dado encontrado",
  nenhumaTransacaoPeriodo: "Não há transações para o período selecionado.",
  semCategoria: "Sem categoria",
  erroObterResumo: "Erro ao obter resumo mensal:",
};
