export const stringsTransacoes = {
  transacoes: "Transações",
  novaTransacao: "Nova Transação",
  editarTransacao: "Editar Transação",
  detalhesTransacao: "Detalhes da Transação",
  receita: "Receita",
  despesa: "Despesa",
  titulo: "Título",
  valor: "Valor",
  tipo: "Tipo",
  categoria: "Categoria",
  data: "Data",
  observacoes: "Observações",
  adicionarTransacao: "Adicionar Transação",
  salvarTransacao: "Salvar Transação",
  excluirTransacao: "Excluir Transação",
  carregandoTransacoes: "Carregando transações",
  salvandoTransacao: "Salvando transação",
  excluindoTransacao: "Excluindo transação",
  carregandoCategorias: "Carregando categorias",
  salvandoCategoria: "Salvando categoria",
  excluindoCategoria: "Excluindo categoria",
  transacaoSalva: "Transação salva com sucesso!",
  transacaoExcluida: "Transação excluída com sucesso!",
  erroSalvarTransacao: "Erro ao salvar transação",
  erroExcluirTransacao: "Erro ao excluir transação",
  erroCarregarTransacoes: "Erro ao carregar transações",
  confirmarExclusaoTransacao: "Tem certeza que deseja excluir esta transação?",
  nenhumaTransacaoEncontrada: "Nenhuma transação encontrada",
  adicionePrimeiraTransacao:
    "Adicione sua primeira transação ou ajuste os filtros",
  semResultados: "Nenhuma transação encontrada com os filtros aplicados",
  filtrarPorTipo: "Filtrar por tipo",
  filtrarPorCategoria: "Filtrar por categoria",
  filtrarPorData: "Filtrar por data",
  todosTipos: "Todos os tipos",
  todasCategorias: "Todas as categorias",
  totalIncome: "Total de Receitas",
  totalExpense: "Total de Despesas",
  balance: "Saldo",
  totalTransacoes: "Total Transações",
  filtros: "Filtros",
  limparFiltros: "Limpar Filtros",
  buscarTitulo: "Buscar por título",
  todos: "Todos",
  todas: "Todas",
  receitas: "Receitas",
  despesas: "Despesas",
  tipoLabel: "Tipo",
  categoriaLabel: "Categoria",
  filtroTipo: "Tipo",
  filtroCategoria: "Categoria",
  filtroBusca: "Busca",
  voltarDashboard: "Voltar ao Dashboard",
  placeholderTitulo: "Digite o título da transação",
  placeholderValor: "0,00",
  placeholderCategoria: "Selecione uma categoria",
  placeholderObservacoes: "Observações adicionais (opcional)",
  tituloObrigatorio: "Título é obrigatório",
  tituloMinimo: "Título deve ter pelo menos 3 caracteres",
  valorObrigatorio: "Valor é obrigatório",
  valorMinimoMaiorQueZero: "Valor deve ser maior que zero",
  tipoObrigatorio: "Tipo é obrigatório",
  categoriaObrigatoria: "Categoria é obrigatória",
  dataObrigatoria: "Data é obrigatória",
};
